server:
  port: 7001

eureka:
  instance:
    hostname: localhost

  client:
    register-with-eureka: false #是否向eureka中注册 false，因为这里是eureka的服务端，其他客户端需要在这里注册
    fetchRegistry: false #是否获取注册信息 服务端不需要获取注册信息 而是在这里注册的客户端需要获取注册信息
    service-url:
      defaultZone: http://localhost:7001/eureka #eurakaServer端地址